### PR TITLE
Remove filtering inside compose 

### PR DESCRIPTION
**Pull request by istarkov**
1) With filtering `compose` does not have the well know definition of this function as like as in your comments https://github.com/reactjs/redux/blob/master/src/compose.js#L7-L9
2) Then I accidentally pass something what is not a function into compose, the only thing I could expect is an error not silent code execution. (there is no need at all to pass anything which is not a function)
3) Typed definition of compose (even you does not use it) will be really hard to create with filtering.

So I suggest you to remove this line.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
As a developer I expect my code to throw an Error not eat it. Also I strongly opposite to extra useless computations in redux. Why not to filter functions outside of `compose` if you really need this?
So big 👍 to this PR

**Comment by alexeyraspopov** [comment]
This breaks the @evilj0e's use case described in https://github.com/reactjs/redux/pull/2073

**Comment by alexeyraspopov** [comment]
But throwing errors explicitly is definitely a better thing.

**Comment by jimbolla** [comment]
What if it were to only filter out falsey?

**Comment by chicoxyzzy** [comment]
@jimbolla why filter something at all?
The problem described in #2073 solves in many ways by one-liner. But the fix from #2073 is a fix of a particular codebase and it leads to ommited errors and performance regressions in others people code

**Comment by chicoxyzzy** [comment]
One can filter everything he wants to outside of compose. It's so easy I can't even

**Comment by timdorr** [comment]
Good points being made. Thanks!
